format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
$docker_context\
$cmd_duration\
$fill\
$time\
$line_break\
$python\
$character"""

# Disable the blank line at the start of the prompt
add_newline = false

[directory]
style = "#75c5fa"
fish_style_pwd_dir_length = 1

[character]
success_symbol = "[❯](purple)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](green)"

[c]
symbol = ""
style = "fg:#6EB0D4"
format = '[$symbol ($version) ]($style)'

[docker_context]
symbol = ""
style = "fg:#6EB0D4"
format = '[$symbol $context ]($style) $path'

[elixir]
symbol = ""
style = "fg:#6EB0D4"
format = '[$symbol ($version) ]($style)'

[elm]
symbol = ""
style = "fg:#6EB0D4"
format = '[$symbol ($version) ]($style)'

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed )]($style)"
style = "cyan"
conflicted = "="
untracked = "⇡"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
stashed = "≡"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[golang]
symbol = ""
style = "fg:cyan"
format = '[$symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "fg:#605084"
format = '[$symbol ($version) ]($style)'

[java]
symbol = ""
style = "fg:#da3b33"
format = '[$symbol ($version) ]($style)'

[julia]
symbol = ""
style = "fg:#6c82db"
format = '[$symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#95cc48"
format = '[$symbol ($version) ]($style)'

[nim]
symbol = ""
style = "fg:#ddc057"
format = '[$symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#fffeee"
format = '[$symbol ($version) ]($style)'

[scala]
symbol = ""
style = "fg:#cd422d"
format = '[$symbol ($version) ]($style)'

[cmd_duration]
format = "[$duration ]($style)"
style = "yellow"

[python]
format = "[$virtualenv]($style) "
style = "bright-black"

[time]
disabled = false
time_format = "%T" # 24 Hour:Minute:Second Format
style = "fg:#626167"
format = '[$time]($style)'

[fill]
symbol = ' '

